### ISSUE TITLE
Can I get all historical scenes?

### ISSUE THREAD

**Issue by n3g2** [hrueger/obs-studio-node-docs#3]
How to get all the historical scenes, when the program just started?

**Comment by hrueger** [comment]
Hi @n3g2,
What do you mean with historicyl scenes?
`obs-studio-node` is not a connector to OBS Studio, but instead a library for usage in your own application. That means, there will never be any scenes when you start your program. Instead, you need to create them. Does that help?

**Comment by n3g2** [comment]
I see. Thank you.

**Comment by hrueger** [comment]
You're welcome 👍
